task :default => 'euler.box'

task :clean do
  sh 'vagrant destroy -f'
  sh 'vagrant box remove euler virtualbox || true'
  sh 'rm -f noted.box'
end

file 'euler.box' => FileList['site.pp', 'modules/**/*'] do
  sh 'vagrant destroy -f'
  sh 'vagrant box remove euler virtualbox || true'
  sh 'vagrant up'
  sh 'rm -f euler.box'
  sh 'vagrant package --output euler.box'
  sh 'vagrant destroy -f'
end
